Sections_to_plot = {1:{'c':1640,
                        'd':1350,
                        'e':425,
                        'f':730,
                        'tlat1':69,
                        'tlat2':84.5,
                        'tlon1':-144,
                        'tlon2':-144,
                        'name':'Section_Alaskan',
                        'col':'maroon'},
                   }

Areas_to_plot = {1:{'lat1':69,
                   'lat2':72,
                   'lon1':-153,
                   'lon2':-135,
                   'c':'r',
                   'name':'AlaskanShelf'},
                2:{'lat1':73,
                   'lat2':77,
                   'lon1':-152,
                   'lon2':-135,
                   'c':'g',
                   'name':'CanadaBasin'},
                 3:{'lat1':79,
                   'lat2':83,
                   'lon1':-153,
                   'lon2':-125,
                   'c':'cyan',
                   'name':'DeepBasin'},
                 4:{'lat1':72.5,
                   'lat2':74,
                   'lon1':-160,
                   'lon2':-155,
                   'c':'Navy',
                   'name':'Chukchi shelf'}}
